### ISSUE TITLE
Crate namespace conflict

### ISSUE THREAD

**Issue by alice-i-cecile** [aatifsyed/sprawl#1]
Hi! I was intending to use the `sprawl` name for https://github.com/dioxuslabs/sprawl, as discussed and publicly announced in https://github.com/DioxusLabs/sprawl/issues/11 before the crate was reserved.

Is there any chance I could convince you to pass ownership of the crates.io spot to our team?

**Comment by alice-i-cecile** [comment]
It looks like this crate is made in good faith though, even if it is immature. So I'll see what I can do about a rename on my end...

**Comment by aatifsyed** [comment]
Happy to pass it to you - this is going to be a slow-moving crate :)

**Comment by aatifsyed** [comment]
I have invited you (alice-i-cecile) as an owner of `sprawl`, which I think is the right thing to do?
Happy to take instruction here, and also happy to go with whatever you and your team decide.

**Comment by alice-i-cecile** [comment]
Honestly, thank you so much. That said, the team and I think that `sprawl` is a better fit for a web crawler than a layout library. I'm happy to let you have it; we have no shortage of good alternative names.

I've declined the invitation and we'll pick a new name <3
